"""
Django settings for SGH_API project.

Generated by 'django-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "ru4&0wf&j@#9itcg!)(e-!tllidh(@bk3xfk1ux+$hxb)f1+7-"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    "django_filters",
    "corsheaders",
    "rest_framework",
    "ficha.apps.FichaConfig",
    "archivoestudio.apps.ArchivoestudioConfig",
    "orinasimple.apps.OrinasimpleConfig",
    "orinasimpledatoslab.apps.OrinasimpledatoslabConfig",
    "comorbilidades.apps.ComorbilidadesConfig",
    "enfermedad.apps.EnfermedadConfig",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "consulta.apps.ConsultaConfig",
    'estudio.apps.EstudioConfig',
    'ordenestudio.apps.OrdenestudioConfig',
    "efectoadverso.apps.EfectoAdversoConfig",
    "efectoadverso_consulta.apps.EfectoadversoConsultaConfig",
    "eventocardiovascular.apps.EventocardiovascularConfig",
    "eventocardio_ficha.apps.EventocardioFichaConfig",
    "fames.apps.FamesConfig",
    "archivo.apps.ArchivoConfig",
    "turno.apps.TurnoConfig",
    "turno_distribucion.apps.TurnoDistribucionConfig",
    "famesficha.apps.FamesFichaConfig",
    "manifestacion.apps.ManifestacionConfig",
    "maniextraarti.apps.ManiExtraArtiConfig",
    "panolab.apps.PanolabConfig",
]


MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "SGH_API.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ]
        },
    }
]

WSGI_APPLICATION = "SGH_API.wsgi.application"


# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql_psycopg2",
        "NAME": "SGHBackEnd",
        "USER": "postgres",
        "PASSWORD": "0909",
        "HOST": "localhost",
        "PORT": "5432",
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = "/static/"

CORS_ORIGIN_WHITELIST = "localhost:8000/"

CORS_ORIGIN_ALLOW_ALL = True

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")