# Generated by Django 2.1.7 on 2019-03-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrinaSimpleDL',
            fields=[
                ('codorinadl', models.AutoField(primary_key=True, serialize=False)),
                ('codorina', models.IntegerField()),
                ('coddatoslab', models.IntegerField()),
            ],
            options={
                'ordering': ('codorinadl',),
            },
        ),
    ]
