# Generated by Django 2.1.7 on 2019-02-25 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EfectoAdversoConsulta',
            fields=[
                ('codefecaddl', models.AutoField(primary_key=True, serialize=False)),
                ('codefecad', models.IntegerField()),
                ('coddatoslab', models.IntegerField()),
            ],
            options={
                'ordering': ('codefecaddl',),
            },
        ),
    ]
