# Generated by Django 2.1.7 on 2019-02-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCardiovascularFicha',
            fields=[
                ('codevencardofic', models.AutoField(primary_key=True, serialize=False)),
                ('codevencardio', models.IntegerField()),
                ('codficha', models.IntegerField()),
            ],
            options={
                'ordering': ('codevencardofic',),
            },
        ),
    ]
