# Generated by Django 2.1.7 on 2019-03-02 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventocardiovascular', '0001_initial'),
        ('eventocardio_ficha', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventocardiovascularficha',
            name='codevencardio',
        ),
        migrations.AddField(
            model_name='eventocardiovascularficha',
            name='codevencardio',
            field=models.ManyToManyField(null=True, to='eventocardiovascular.EventoCardiovascular'),
        ),
    ]
