# Generated by Django 2.1.7 on 2019-03-02 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventocardio_ficha', '0002_auto_20190302_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventocardiovascularficha',
            name='codficha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ficha.Ficha'),
        ),
    ]
