# Generated by Django 2.1.7 on 2019-03-02 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventocardiovascular', '0001_initial'),
        ('eventocardio_ficha', '0003_auto_20190302_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventocardiovascularficha',
            name='codevencardio',
        ),
        migrations.AddField(
            model_name='eventocardiovascularficha',
            name='codevencardio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='eventocardiovascular.EventoCardiovascular'),
        ),
    ]
