# Generated by Django 2.1.7 on 2019-03-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manifestacion',
            fields=[
                ('codmanifficha', models.AutoField(primary_key=True, serialize=False)),
                ('codmanif', models.IntegerField()),
                ('codficha', models.IntegerField()),
            ],
            options={
                'ordering': ('codmanifficha',),
            },
        ),
    ]
