# Generated by Django 2.1.7 on 2019-03-02 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='codficha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ficha.Ficha'),
        ),
    ]
