# Generated by Django 2.1.7 on 2019-02-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EfectoAdverso',
            fields=[
                ('codefecad', models.AutoField(primary_key=True, serialize=False)),
                ('codusuario', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('fechacreada', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ('codefecad',),
            },
        ),
    ]
