# Generated by Django 2.1.7 on 2019-02-25 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ficha',
            options={'ordering': ('codficha',)},
        ),
    ]
