# Generated by Django 2.1.7 on 2019-03-02 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0003_auto_20190302_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='codpaciente',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ficha.Paciente'),
        ),
    ]
