# Generated by Django 2.1.7 on 2019-03-02 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ficha', '0004_auto_20190302_1742'),
        ('ficha', '0002_auto_20190224_2216'),
    ]

    operations = [
    ]
