# Generated by Django 2.1.7 on 2019-03-02 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('famesficha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='famesficha',
            name='codfame',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='fames.Fames'),
        ),
        migrations.AlterField(
            model_name='famesficha',
            name='codficha',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ficha.Ficha'),
        ),
    ]
